apiVersion: v1alpha
kind: imagerunner
sauce:
region: us-west-1
suites:
  - name: run sauce test
    image: lsimity/photontest:0.0.4
    imagePullAuth:
        user: ${SAUCE_IMAGE_USER}
        token: ${SAUCE_IMAGE_TOKEN}
    entrypoint: "sh -c 'cd workdir/photon; npx wdio wdio.conf.js'"
    artifacts:
      - "/path/inside/container/file.log"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}